elementary/greeter

src/Indicators/IndicatorBar.vala
* Update GPL Header
* GObject-style construction
=> IndicatorBar.vala: GObject-style construct

src/UserListActor.vala, src/Widgets/LoginBox.vala
Fixes #80.
The avatar itself is in an EventBox so we need to capture that event and tell greeter to make a switch.
=> Switch to the target user when clicking the avatar

src/LoginOptions/LoginOption.vala, src/LoginOptions/UserLogin.vala
works around LightDM returning null background strings in newer versions
fixes #88
=> Get wallpaper manually if LightDM doesn't work

CMakeLists.txt, README.md, src/SettingsDaemon.vala, src/config.vala.cmake
This updates Greeter to launch the needed GSD processes in Juno
Fixes #99 
As an aside, this does not fix HiDPI. Greeter will now require a mutter compositor in order to fix this and that is outside the scope of this branch
=> Update GSD processes

src/PantheonGreeter.vala
Because Drunk Dan broke everything
Reverts elementary/greeter#101
=> Revert "Launch mutter if we have it"

src/PantheonGreeter.vala
=> Fullscreen the greeter

README.md
Fix #135
This PR is ready to review.
=> Update README to with meson

meson.build, src/meson.build
This has been the correct way since meson 0.37.
=> Meson: correct install_path

src/Cards/BackgroundImage.vala, src/Cards/UserCard.vala
=> Always show usernames

src/Cards/UserCard.vala
=> Add check mark on logged in users

src/Cards/UserCard.vala
https://github.com/elementary/greeter/blob/767bbcdce0f3a3189003ed2a6b4b2a6b16b2c9ba/src/LoginOptions/UserLogin.vala#L30
=>  UserCard: use wallpaper path fallback code from old greeter

src/Cards/BackgroundImage.vala
=> BackgroundImage: Fix light bleed on corners

data/DateTime.css
=> DateTime.CSS: workaround shadow issue with large fonts

src/Cards/ManualCard.vala
* Add an icon to the card
* Add an icon to the username field
* Adjust padding to match other cards
* Add margin on the card so the shadow shows
=> ManualCard: Adjust styling

src/CapsLockRevealer.vala, src/Cards/ManualCard.vala, src/Cards/UserCard.vala, src/meson.build
=> Add a caps lock indicator

src/Cards/BaseCard.vala, src/Cards/ManualCard.vala, src/Cards/UserCard.vala, src/MainWindow.vala
Uses the same method we use in Switchboard
This doesn't seem to work with the manual entry card at all
=> Grab entry focus when typing

compositor/WindowManager.vala
adds "gl_video_memory_purged" signal to retrieve OpenGL textures. Divided the responsibilities of setting or updating the background screen without static methods and without calling the method in object construction.
=> Nvidia drivers: Refresh background after suspend

src/MainWindow.vala
=> MainWindow: Hard code stylesheet and icons

src/Application.vala, src/MainWindow.vala
Reverts elementary/greeter#247
Looks like there are a couple issues here regarding HiDPI and media keys
=> Revert "Fix keyboard focus and wingpanel in greeter"

src/Application.vala, src/MainWindow.vala
Reverts elementary/greeter#249
Nevermind, it was the other commit that did it
=> Revert "Revert "Fix keyboard focus and wingpanel in greeter""

compositor/DBusAccelerator.vala
=> Media Keys: Do not send unwanted signals

src/Cards/UserCard.vala
=> UserCard: Make session button insensitive when user is logged in

src/CapsLockRevealer.vala
=> CapsLockRevealer: also warn about numlock

src/SessionButton.vala
=> Make sessions a listbox of modelbuttons

debian/control
=> Add AccountsService dep

src/MainWindow.vala
=> MainWindow: If user list length is 0, try to launch initial setup

.editorconfig, data/create-symlink.py, data/io.elementary.greeter.AccountsService.policy, data/io.elementary.greeter.AccountsService.xml, data/meson.build, po/POTFILES, src/CapsLockRevealer.vala, src/Cards/UserCard.vala, src/DateTimeWidget.vala, src/GreeterAccountsServicePlugin.vala, src/MainWindow.vala, src/meson.build
We then need to replace the GSettings with this DBus parameter that is now exposed
=> Use the current selected user time format

src/MainWindow.vala
=> Add mouse scroll navigation

src/MainWindow.vala
=> Always select the first session and use the latest session from the user

src/PasswordEntry.vala
=> Remove password entry placeholder

data/greeter.appdata.xml.in, meson.build
https://github.com/elementary/greeter/compare/5.0...master
=> Release 5.0.1

compositor/SystemBackground.vala, compositor/WindowManager.vala
This should fix https://github.com/elementary/greeter/issues/379.
This is exactly the same fix as https://github.com/elementary/gala/pull/635/commits/cd54f327bfb4226a7ac0d02912b14f5bcd03e24a.
=> Fix MetaBackgroundActor build errors

compositor/DBusAccelerator.vala
=> DBusAccelerator: the "accelerator-activated" has changed its arguments

README.md
=> README: Specify required Granite version

compositor/DBusAccelerator.vala
This was added in g-s-d 3.33.0 [0].
[0]: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/GNOME_SETTINGS_DAEMON_3_33_0/NEWS#L8
Same as https://github.com/elementary/gala/pull/760
=> Support g-s-d UngrabAccelerators API

data/greeter.appdata.xml.in, meson.build
Just localization. The only code change was the mlock thing which is a fix for ARM so not worth mentioning
=> Release 5.0.4

compositor/KeyboardManager.vala
Same as https://github.com/elementary/gala/pull/910
=> compositor: KeyboardManager: listen to sources key

data/Card.css, src/MainWindow.vala, src/Widgets/BackgroundImage.vala
=> Switch stylesheet to greenfield

.github/workflows/main.yml, README.md, src/Cards/UserCard.vala, src/meson.build
=> UserCard: Replace Granite.Avatar with Hdy.Avatar

compositor/SystemBackground.vala, compositor/WindowManager.vala, vapi/Clutter-7.metadata, vapi/Meta-7.metadata, vapi/libmutter.vapi
Fixes #484 
Update the vapis and make similar changes to what we did in https://github.com/elementary/gala/pull/854 to make this not hang when running against mutter-7
=> compositor: Support mutter-7

.github/workflows/main.yml, src/Cards/BaseCard.vala, src/Cards/ManualCard.vala, src/Cards/UserCard.vala
Complimentary to #505. Looks like more than it is because it wraps some long lines for legibility.
=> UserCard: Code cleanup

src/Cards/UserCard.vala
Fixes #530 by moving margin from the username label to the form grid
=> UserCard: fix focus glow on password entry

src/Cards/UserCard.vala
=> UserCard: use avatar from FileIcon

src/Cards/UserCard.vala, src/MainWindow.vala
Fixes #512 
Fixes #388
For now, we stick with the manual navigation and scroll handling, so no 1:1 swipies
=> Use Hdy.Carousel instead of overlay magic

src/Cards/UserCard.vala, src/PantheonAccountsServicePlugin.vala
=> Set users' preferred accent color

data/greeter.appdata.xml.in, src/MainWindow.vala, src/Widgets/DateTimeWidget.vala
=> MainWindow: Hide datetime when no users

data/Check.css, data/greeter.gresource.xml, src/Cards/UserCard.vala
=> UserCard: use accent color for logged_in check

data/greeter.appdata.xml.in
In the interest of https://github.com/elementary/feedback/pull/64
=> AppData: Change name

data/io.elementary.greeter.policy.in, data/meson.build
Related to https://github.com/elementary/greeter/pull/624
=> Fix double login authentication

.github/workflows/main.yml
We are now using elementary 7 as unstable container
=> ci: Switch to mutter-10

compositor/Dialogs.vala
A copy of https://github.com/elementary/gala/pull/1515
=> AccessDialog: Copy changes from Gala

compositor/Dialogs.vala, compositor/WindowManager.vala
A copy of https://github.com/elementary/gala/pull/1516
=> WindowManager: confirm_display_change() Fixes

compositor/KeyboardManager.vala
Same as https://github.com/elementary/gala/pull/1626
=> KeyboardManager: Set keyboard layout on startup

data/40-io.elementary.greeter.conf, data/meson.build
In combination with https://github.com/elementary/greeter/pull/650
=> meson: Install lightdm config

src/Cards/UserCard.vala, src/PantheonAccountsServicePlugin.vala
Requires https://github.com/elementary/settings-daemon/pull/73
Makes dyslexia-friendly font work in Greeter.
=> Use users' fonts

debian/control
Needed to sync many settings to the greeter
=> Control: add runtime depends on Settings Daemon 1.3.0

data/greeter.metainfo.xml.in, src/Cards/UserCard.vala
=> UserCard: Handle click event using `Gtk.GestureMultiPress`

data/greeter.metainfo.xml.in, src/MainWindow.vala
=> Don't reset user settings when entering wrong credentials

src/Cards/UserCard.vala, src/PantheonAccountsServicePlugin.vala
Requires https://github.com/elementary/settings-daemon/pull/126
Fixes https://github.com/elementary/greeter/issues/130
Fixes https://github.com/elementary/greeter/issues/216
=> Sync orientation lock

src/MainWindow.vala
Fixes https://github.com/elementary/greeter/issues/634
Closes https://github.com/elementary/greeter/issues/333
=> Don't allow scrolling while login attempt is in progress

compositor/WindowManager.vala, src/Application.vala
Closes https://github.com/elementary/greeter/issues/342
Fixes https://github.com/elementary/greeter/issues/485
Fixes https://github.com/elementary/greeter/issues/264
=> Compositor: Add fade-in animation

compositor/WindowManager.vala, src/Application.vala
Reverts elementary/greeter#697
Should fix https://github.com/elementary/triage/issues/445
=> Revert "Compositor: Add fade-in animation"

compositor/WindowManager.vala
=> Compositor: disable tiling shortcuts

src/MainWindow.vala
=> MainWindow: grid to box

src/MainWindow.vala
=> MainWindow: don't use dialog run

src/Cards/BaseCard.vala
Can't subclass Revealer in GTK 4
=> BaseCard: subclass box

src/Widgets/SessionButton.vala
No access to ModelButton in GTK 4
=> SessionButton: build menu from model

src/MainWindow.vala
Reverts elementary/greeter#733
Seems to have caused #734
=> Revert "MainWindow: Better detect when running in live session"

compositor/Background/BackgroundManager.vala
Fixes https://github.com/elementary/greeter/issues/737
The simplest solution for now. To fix this properly we need to implement rounded corners shader effect, and one copied from mutter gives very bad results for some reason.
=> Remove rounded corners

data/io.elementary.greeter.desktop.in, data/meson.build
It is not meant to be visible anyway
=> Do not translate the Greeter session file

data/Application.css
Fixes #767 
Specify the window background since popovers also get .background
=> CSS: specify window.background opacity

data/io.elementary.greeter.conf
Closes https://github.com/elementary/greeter/issues/356
Closes https://github.com/elementary/greeter/issues/360
=> Remove unused values from config

data/compositor.gschema.xml, src/MainWindow.vala, src/Settings.vala
=> Use gsettings to store last user

src/Application.vala, src/MainWindow.vala, src/Widgets/SessionButton.vala
There's no `hierarchy_changed` in Gtk4, so move "select-session" action into Application
=> Move session action into application

src/Cards/UserCard.vala, src/MainWindow.vala, src/Settings.vala
Significantly simplifies the code and uses a modern pattern for synchronizing settings. While we're here update copyright headers
=> Set power settings of active user

src/MainWindow.vala
Allows us to get rid of these ugly notifies
It doesn't make sense to connect to daemon asynchronously because the window is invisible until the users are loaded, which is when we connect to the daemon
While we're here use box for the bottom buttons and don't store them in the main window variables
=> Connect to lightdm daemon early

src/Widgets/SessionButton.vala
=> SessionButton: subclass bin

compositor/PointerLocator.vala, compositor/WindowManager.vala, compositor/Zoom.vala, compositor/meson.build, vapi/Clutter-14-custom.vala, vapi/Clutter-15-custom.vala, vapi/Clutter-16.metadata, vapi/Cogl-16-custom.vala, vapi/Cogl-16.metadata, vapi/Meta-16.metadata, vapi/Mtk-16.metadata, vapi/libmutter-16.deps, vapi/libmutter-16.vapi, vapi/libmutter.vapi, vapi/meson.build, vapi/mutter-clutter-16.deps, vapi/mutter-clutter-16.vapi, vapi/mutter-clutter.vapi, vapi/mutter-cogl-14.vapi, vapi/mutter-cogl-16.deps, vapi/mutter-cogl-16.vapi, vapi/mutter-mtk-13.vapi, vapi/mutter-mtk-16.vapi
Closes https://github.com/elementary/greeter/issues/790
=> Start the port to Mutter 48

compositor/BackgroundBlurEffect.vala, compositor/BlurManager.vala, compositor/PantheonShell.vala, compositor/ShellClients/NotificationsClient.vala, compositor/WindowManager.vala, compositor/meson.build, compositor/protocol/pantheon-desktop-shell-v1.xml, compositor/protocol/pantheon-desktop-shell.vapi, protocol/pantheon-desktop-shell-v1.xml, protocol/pantheon-desktop-shell.vapi, vapi/mutter-clutter.vapi, vapi/mutter-cogl-14.vapi, vapi/mutter-cogl.vapi
Fixes https://github.com/elementary/greeter/issues/825
=> Add blur protocol
