elementary/greeter

src/Widgets/CredentialsArea.vala
src/Widgets/LoginBox.vala

* Set width request on the grid instead of on its children so we only have the magic number in one place
* Since this is a revealer subclass now, `reveal_child` is already public

CredentialsArea.vala: set width on grid, use reveal_child

---

src/Gateways/DummyGateway.vala
src/Gateways/LightDMGateway.vala
src/Gateways/LoginGateway.vala
src/Interfaces/Credentials.vala
src/Interfaces/LoginMask.vala
src/LoginOptions/GuestLogin.vala
src/LoginOptions/LoginOption.vala
src/LoginOptions/ManualLogin.vala
src/LoginOptions/UserLogin.vala
src/Widgets/CredentialsArea.vala
src/Widgets/FingerprintCredentials.vala
src/Widgets/LoginBox.vala
src/Widgets/LoginButtonCredentials.vala
src/Widgets/PasswordCredentials.vala
src/Widgets/TimeLabel.vala
src/Widgets/Wallpaper.vala

Updates the address of the Free Software Foundation in the license headers
Fixes https://bugs.launchpad.net/pantheon-greeter/+bug/1653413

Update FSF address

---

data/Greeter.css

LightDM complains about the icon shadow property being renamed 
`Theme parsing error: Greeter.css:37:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'`

Update css to use -gtk-icon-shadow

---

src/Widgets/CredentialsArea.vala

`margin_left` and `margin_right` were deprecated in GTK 3.12, so let's update to the newer properties

update to margin_start and margin_end

---

meson.build
meson_options.txt
src/SettingsDaemon.vala
src/meson.build

This pull request is a straight-forward transformation of my fedora downstream patch into a conditional compilation patch that should be acceptable for merging upstream.
I intended to preserve the current behavior - so, the produced code should not change at all for you. But I don't have to carry a downstream patch anymore and can just flip the conditional compilation with a meson build flag.
It introduces a flag similar to the `ubuntu-bionic-patched-vte` flag already used for terminal.
Fixes #179

src/SettingsDaemon: add conditional compilation to account for ubuntu patches

---

src/Application.vala
src/Cards/UserCard.vala

This puts even spacing around the username, which is especially noticeable in collapsed cards. It also ensures that long usernames don't run into the edges of the card

UserCard: Adjust margins around usernames and avatars

---

src/MainWindow.vala

* It seems like we don't need to set the window as transparent, it's already taken care of somewhere else
* We don't need to hexpand the buttons since we set column homogeneous
* Add our datetime, user carousel, and action widgets into a Grid so that they can't overlap each other and we can enforce spacing between them.

MainWindow: Make sure widgets can't overlap and remove dead code

---

src/MainWindow.vala

Also manually `resize` instead of relying on `maximize`, which for some reason doesn't work correctly when the window type is `DESKTOP`.
This seems to supersede some settings like keep below.
Fixes #235 
Fixes #214

MainWindow: Set typehint as DESKTOP

---

src/Application.vala
src/MainWindow.vala

Fixes #144 
Fixes #178 
Although this PR fixes the linked issues (on my system), it is essentially a hack using a timeout to ensure that the current card is the last thing to grab focus, so should be considered temporary or a last resort. A comparatively long delay has been used to try to ensure it is long enough for most systems.
These problem seems to be linked to both the sequence of events at boot (and their relative speed) as well as the sequence of events on starting this application.
In particular there is a longer delay when booting before something happens to steal the focus from the main window compared to when logging in after suspending or logging out.  So the problem might be improved by tweaking the boot sequence.  Note that this focus stealing happens even if the wingpanel …

Fix keyboard focus and wingpanel in greeter

---

meson_options.txt
src/meson.build

In NixOS everything is installed into its own immutable prefix under `/nix/store/*`.
So doing
```
join_paths(get_option('prefix'), get_option('libexecdir') + '/')
```
will never be the `gnome-settings-daemon` prefix.
We also are able to use a `ubuntu-patched-gsd`, so the path problematically turns out to be
```
/usr/lib/gnome-settings-daemon/
```
This patch adds an option `gsd-dir` which will allows us to provide the path to the settings daemon.
Prior to this change we had to build with a patch that would hardcode that path to its proper location.

Add option to declare path to gnome-settings-daemon

---

src/Cards/UserCard.vala

Currently the session button is fill aligned, so it changes position when caps lock is enable. This valigns to the top and creates a size group to make sure it's the same height as the password entry

UserCard: Fix alignment of session button

---

data/MainWindow.css
data/greeter.gresource.xml
src/MainWindow.vala

This waits until we do the maximize-and-focus to also fade the greeter in, avoiding any rendering weirdness that happens earlier (like seeing it scaled to 1x on a 2x display).
I have two issues with this:

Fade greeter in to avoid jank

---

src/MainWindow.vala

When connected to an external monitor, the greeter is sometimes shown on the laptop monitor which is inconvenient if the laptop is closed or half-closed. Therefore I think it would be useful to show the greeter always on the monitor which the mouse pointer is currently on.

Show greeter on the monitor which has the mouse pointer

---

src/MainWindow.vala

Fixes #204 
I'm not sure what the intention was with saving the last user on the revealed signal of a card, and I'm also not sure why it wasn't working.
But surely it's enough to remember the last user that had a successful or unsuccessful login attempt?

Save last user on attempted login

---

src/Cards/BackgroundImage.vala

Fixes #325 
If we had a wallpaper that had a wider aspect ratio than the aspect ratio of the card, we were ending up with some invalid pixbuf copies that were causing corruption.
This branch handles this by ensuring the scaled version we use for the card is at least as big as the desired size and then cropping of either the top and bottom or left and right to center it on the card while preserving the aspect ratio rather than letterboxing.

Handle all background aspect ratios

---

src/Cards/ManualCard.vala
src/Cards/UserCard.vala

For a couple of times now, when I entered my password without really looking at my screen and pressing enter, for a split second I thought that Greeter was never in focus and that I didn't type anything. This was because the password was deleted on the `on_login ()` function. 
This PR just moves the clear password line from `on_login()` to `wrong_credentials()`, that way also when a user types the wrong password, the asterisks will stay in until the User Card starts shaking

Clear password entry on error

---

compositor/DBusAccelerator.vala
compositor/SystemBackground.vala
compositor/Utils.vala
compositor/WindowManager.vala
compositor/meson.build
vapi/libmutter-3.deps
vapi/libmutter-3.vapi
vapi/libmutter-4.deps
vapi/libmutter-4.vapi
vapi/libmutter-5.deps
vapi/libmutter-5.vapi
vapi/libmutter-6.deps
vapi/libmutter-6.vapi
vapi/libmutter.vapi
vapi/mutter-clutter-3.deps
vapi/mutter-clutter-3.vapi
vapi/mutter-clutter-4.deps
vapi/mutter-clutter-4.vapi
vapi/mutter-clutter-5.deps
vapi/mutter-clutter-5.vapi
vapi/mutter-clutter-6.deps
vapi/mutter-clutter-6.vapi
vapi/mutter-cogl-3.deps
vapi/mutter-cogl-3.vapi
vapi/mutter-cogl-4.deps
vapi/mutter-cogl-4.vapi
vapi/mutter-cogl-5.deps
vapi/mutter-cogl-5.vapi
vapi/mutter-cogl-6.deps
vapi/mutter-cogl-6.vapi

I've tested that it builds with mutter 3.34.1 and 3.28.4.
What I've done in `SystemBackground.vala` is probably totally incorrect. A suggestion is welcome on what we actually should be doing.
What I've done is adapted the changes in https://github.com/elementary/gala/pull/566, as it's literally the code copy pasted mostly, to be used here.
Fixes https://github.com/elementary/greeter/issues/120.
It would be fabulous :v: if we could have everything adapted to latest mutter before the end of the year.

Adapt to the latest Mutter API

---

data/greeter.appdata.xml.in
src/MainWindow.vala

Also support the `hide-users-hint` property
Fixes #406

MainWindow: Use bind_property to make sure that either the manual login card is visible or the user cards are there.

---

debian/rules

Seems Ubuntu don't patch GSD as heavily anymore, so we can remove these workarounds. Will be able to remove the conditional compiles from the code in future I guess, but for now this keeps support for `bionic` too.

deb-packaging: remove workaround for Ubuntu patched GSD

---

compositor/DBusAccelerator.vala

Fixes #412 
It would seem that media keys don't currently work in the greeter for the current version of mutter, or newer versions of mutter, so pull in the conditionals from the work we did in Gala to get this working.
Note that trying to use volume media keys currently crashes `gsd-media-keys` in the lightdm session on `bionic` for a reason unrelated to this patch. I'll submit another PR to `os-patches` for that. But this fixes brightness and whatever other media keys that aren't volume we have for now.

Add mutter version conditionals to media keys code

---

compositor/DBusAccelerator.vala

Tiny regression from https://github.com/elementary/greeter/commit/39cba2b462897dbbc10a994e9a8c7c39c4a95178

DBusAccelerator: Fix grab_accelerator argument with Mutter >= 3.22

---

src/SettingsDaemon.vala

The docs on  SettingsSchemaSource get_default say
```
The returned source may actually consist of multiple schema sources from different directories, depending on which directories were given in `XDG_DATA_DIRS` and `GSETTINGS_SCHEMA_DIR`. For this reason, all lookups performed against the default source should probably be done recursively.
```
Without this in NixOS it will not work as intended, as we
have multiple entries in XDG_DATA_DIRS.
(we also happen to use an ubuntu patched gsd for pantheon)

SettingsDaemon: lookup schemas recursive

---

debian/rules

dh-compat 10 defaults to /usr/lib/ARCH/ when we want /usr/libexec (also covered by dh-compat 12)
Fixes #427

rules: Specify libexec directory

---

src/Application.vala

This seemingly causes the greeter to fail to start on architectures other than amd64 and has been removed from all of the other greeters due to it causing sporadic issues with various versions of systemd.
Apparently it doesn't really offer much extra security (which I think was the original point of using it). Discussion and details here:
https://github.com/canonical/lightdm/issues/55#issuecomment-455559561

Remove mlockall

---

debian/control

I think this is why our daily isos aren't working. Nothing depends on lightdm anymore so it's getting stripped out at the autoremove stages at the end of the install.

control: add runtime dep on lightdm

---

compositor/KeyboardManager.vala
compositor/WindowManager.vala
compositor/meson.build

I'm currently working on getting keyboard layout support working in the greeter, including getting the indicator to work and syncing the layouts from the user sessions to the lightdm session. We'll need this class from gala to listen to the GSettings key and set the right layouts.
This will have no effect on keyboard layouts in the greeter at this stage as there won't be any configured in GSettings for the `lightdm` user. I plan to use AccountsService to synchronise these in a future commit.

compositor: Add KeyboardManager class

---

src/Cards/UserCard.vala
src/MainWindow.vala
src/PantheonAccountsServicePlugin.vala

If used in conjunction with https://github.com/elementary/settings-daemon , the list of enabled keyboard layouts and the currently active keyboard layout is synchronized between the user's session and the greeter.
When switching cards in the greeter, the list of layouts and active layout is updated on the fly to reflect the user's preferences.
Currently, the wingpanel keyboard indicator works as it does in the session, i.e. if a user has >1 layouts, it will show and allow switching between them. If they only have 1 layout, it will not be visible while that user's card is selected. But their layout will be active.

Get keyboard layouts from AccountsService

---

compositor/DBusAccelerator.vala
src/MainWindow.vala

`Display.get_pointer` is deprecated, so we replace this with getting the pointer device from the seat. There's a fallback to use the primary monitor here if we can't detect which monitor the mouse is on for some reason. But, I've tested this with multiple monitors and the login dialog still moves onto the monitor the pointer is on.

Fix compiler warnings

---

src/Application.vala

To be used in conjunction with https://github.com/elementary/default-settings/pull/186/ so that we adopt the GSettings overrides, even in the case where they're specific to Pantheon.

Set XDG_CURRENT_DESKTOP to Pantheon

---

src/Widgets/DateTimeWidget.vala

Fix delayed time update after resuming from sleep

---

meson.build
meson_options.txt
src/SettingsDaemon.vala
src/meson.build

We build with this option set to false in Odin already which is causing some confusion when people are building the greeter from git for Odin and it's defaulting to true.
https://github.com/elementary/greeter/pull/417
Since the release CI workflow is already pointing to Odin, we can drop this now and any late-life support we do for bionic will be via backports onto the hera branch, so we just don't backport this commit.

meson: remove ubuntu-patched-gsd option

---

debian/rules

debian: Remove ubuntu-patched-gsd option

---

README.md
src/Cards/ManualCard.vala
src/meson.build

Just some code I noticed could be dusted off when I was spelunking.
- Adds copyright header
- Pulls magic error shaking number out into a const
- Uses modern codestyle throughout
- Adds whitespace for legibility
- Uses `Granite.STYLE_CLASS_ROUNDED` and bumps Granite dep to match
- Uses weak reference to `Gtk.StyleContext` 
- Re-orders and groups the style contexts to keep things organized

ManualCard: Modern code style and cleanup

---

debian/control

We are just spawning wingpanel these days.

Remove libwingpanel from the dependency list

---

compositor/KeyboardManager.vala

Analagous to https://github.com/elementary/gala/pull/1041 and required before https://github.com/elementary/switchboard-plug-keyboard/pull/341 (which adds "ibus" input-source type) can be merged.

KeyboardManager: Ignore input-source type if not "xkb"

---

src/MainWindow.vala

Replaces custom scroll handling with scroll and swipe handling native to Hdy.Carousel. This both gives us 1:1 swiping and long swiping across several cards
The previous method here relied on packing hidden cards into the carousel and hiding and showing all cards for the manual card entry. This doesn't work because you can swipe over to hidden cards, which is bad. So instead, use a Gtk.Stack to switch between manual login and user cards

MainWindow: Use scroll and swipe handling from Hdy

---

src/meson.build

HdyCarousel allow-long-swipes property was added in version 1.1.90:
https://gitlab.gnome.org/GNOME/libhandy/-/blob/master/NEWS#L130

meson: require libhandy-1 >= 1.1.90

---

debian/40-io.elementary.greeter.conf

This is the cause of a very confusing bug that I was experiencing with my nvidia card. After installing the proprietary drivers, it was kind of random as to whether they'd work correctly in a given session. The nvidia X settings application would show up blank, and Xorg would be running using the Nouveau driver, even though the proprietary kernel module was loaded.
It turns out that there's a race condition where lightdm can start and launch Xorg before the nvidia kernel module is loaded. Meaning that when Xorg does its autoconfiguration, it loads the Nouveau Xorg driver for the card instead of the proprietary one, leading to all kinds of badness.
This causes lightdm to wait for the graphics devices to be ready before trying to spawn the greeter.
Info found here: …

Wait for graphics drivers to be ready before launching Xorg

---

compositor/BackgroundManager.vala
compositor/BackgroundUtils.vala
compositor/DBusBackgroundManager.vala
compositor/SystemBackground.vala
compositor/WindowManager.vala
compositor/meson.build

Allows the compositor to tell Wingpanel about the colour of the background so it can adapt its transparency, as it does under Gala.
This code is 99% directly copied from the Gala plugin, so I haven't updated any of the copyright headers.

compositor: Add Wingpanel Background interface

---

compositor/Utils.vala
compositor/WindowManager.vala
po/nl.po

Removes unused functions from WindowManager and Utils classes and fixes a compiler warning ``warning: Switch does not handle `UNMAXIMIZE' of enum `Meta.SizeChange'``.

Compositor: Remove unused functions

---

debian/install

We still need to make sure this package installs files to this directory because the latest package just doesn't install this file at all.

Add Lightdm conf dir to Install

---

src/Cards/UserCard.vala
src/MainWindow.vala

* Set user's accent color globally using `org.gnome.desktop.interface gtk-theme`
* Style each user's check individually

Improve handling of users' accent color

---

src/Cards/UserCard.vala
src/PantheonAccountsServicePlugin.vala

Sets user cursor blinking settings, cursor size, text size and option to locate the pointer (~doesn't work yet because it requires implementation in compositor~ #674)
Requires https://github.com/elementary/settings-daemon/pull/71
Fixes https://github.com/elementary/greeter/issues/596

Use user's interface settings

---

.github/workflows/main.yml

This allows us to specify the mutter version instead of using globs (useful as some Ubuntu version have two mutter version in the repository while transitioning to the next version)

ci: Specify the mutter package to use

---

compositor/WindowManager.vala
src/Application.vala

Closes https://github.com/elementary/greeter/pull/702
Uses simpler way to animate fade-in. Should not produce any glitches whatsoever.

Simpler fade-in animation

---

src/MainWindow.vala

This isn't a thing we can do in GTK 4 and it also doesn't make sense anymore with the wallpaper background

MainWindow: don't force dark style for buttons

---

compositor/WindowManager.vala
src/Application.vala

Just the panel launching part of #726 
afaict this part works as expected

WindowManager: launch panel as subprocess

---

data/DateTime.css
src/MainWindow.vala
src/Widgets/DateTimeWidget.vala

Make the datetime widget larger, bolder, with softer shadows, and more towards the center of the display

Make datetime widget larger

---

compositor/WindowManager.vala
compositor/main.vala
data/io.elementary.greeter.desktop.in.in
src/Application.vala

Allows to make sure that the greeter will be launched when the compositor is ready, also allow us to use the right API on wayland.

Make the compositor be the first program to launch

---

compositor/WindowManager.vala
compositor/Zoom.vala
compositor/meson.build
data/compositor.gschema.xml
data/meson.build
meson.build

Fixes https://github.com/elementary/greeter/issues/540

Implement zoom

---

.github/workflows/main.yml

The stable and unstable images are no longer jammy but noble
The same fix with https://github.com/elementary/gala/pull/2073

ci: Update mutter version for noble

---

.github/workflows/main.yml
compositor/Background/Background.vala
compositor/Background/BackgroundContainer.vala
compositor/WindowManager.vala
compositor/meson.build
vapi/Clutter-15-custom.vala
vapi/Clutter-15.metadata
vapi/Cogl-15-custom.vala
vapi/Cogl-15.metadata
vapi/Meta-15.metadata
vapi/Mtk-15.metadata
vapi/libmutter-15.deps
vapi/libmutter-15.vapi
vapi/libmutter.vapi
vapi/meson.build
vapi/mutter-clutter-15.deps
vapi/mutter-clutter-15.vapi
vapi/mutter-clutter.vapi
vapi/mutter-cogl-14.vapi
vapi/mutter-cogl-15.deps
vapi/mutter-cogl-15.vapi
vapi/mutter-cogl-pango-15.vapi
vapi/mutter-cogl-pango.vapi
vapi/mutter-mtk-13.vapi
vapi/mutter-mtk-15.vapi

Fixes #744 
Can rebase merge if desired

Add Mutter 47 support

---

compositor/WindowManager.vala
src/Application.vala
src/Cards/UserCard.vala
src/PantheonAccountsServicePlugin.vala
src/SettingsPortal.vala
src/meson.build

Fixes https://github.com/elementary/greeter/issues/688
Closes #563
Closes #499
This branch implements mini settings portal inside of the greeter itself and exposes it via dbus which allows granite to correctly get dark style preference

Add dark style support

---

src/FPrintUtils.vala

1. Update copyright header
2. Replace random commented out code with TODO
3. Fix typos

Cleanup FPrintUtils

---

src/MainWindow.vala
src/Widgets/DateTimeWidget.vala

1. User's time preference can't change while we're in Greeter, so no need to create binding for it.
2. Add copyright header to DateTimeWidget.vala
3. Move LoginManager inside the class
4. Use setter instead of `notify`
5. And some other changes to make code cleaner and more readable

Cleanup DateTimeWidget

---

src/Application.vala

- Motivation: elementary/session-settings#91

Do not try to fallback to x11 session when it is unavailable
